### ISSUE TITLE
TypeError: Cannot read property 'page' of undefined

### ISSUE THREAD

**Issue by ajoecker** [And93/protractor-puppeteer-plugin#23]
Hi,

I have the problem that with our cucumber/protractor setup I get a `TypeError: Cannot read property 'page' of undefined` for the following 

```
'use strict';
const {browser} = require('protractor');

function PuppeteerPage() {
  this.runPuppeteer = () =>  {
    browser.get('http://angular.io');
    browser.cdp.page.screenshot({path: 'screenshot.png'});
  };
}
```

the `get` seems to work, as it navigates to angular, but then the following is printed out in console:

```
 × failed
      TypeError: Cannot read property 'page' of undefined
          at PuppeteerPage.runPuppeteer (C:\Users\me\WebstormProjects\ui\e2e\tests\pageobjects\puppeteerPage.js:8:17)
          at World.<anonymous> (C:\Users\me\WebstormProjects\ui\e2e\tests\step_definitions\puppeteer.js:8:24)
```
and my `puppeteer.conf.json`
```
{
  "connectToBrowser": false,
  "timeout": 30000,
  "logLevel": "info"
}
```
my `protractor.cucumber.conf.js` is the following: 
```
'use strict';
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';
let path = require('path'),
  cucumberReportName,
  downloadloc = path.join(__dirname, '../tests/downloads');

if (process.env.BUILD_ID) { //running on jenkins
  downloadloc = '/var/tmp/e2e/uploads';
}

if (process.env.BUILD_TAG) { //keep management result unique per build
  cucumberReportName = `report-${process.env.BUILD_TAG}-management.json`;
} else {
  cucumberReportName = 'report.json';
}

exports.config = {
  framework: 'custom',
  frameworkPath: require.resolve('protractor-cucumber-framework'),
  seleniumAddress: 'http://127.0.0.1:4444/wd/hub',
  jsonReportsDirOutput: 'reports/json',
  downloadsDir: downloadloc,
  browserErrorsDirOutput: 'browserErrors',
  allScriptsTimeout: 125000,
  getPageTimeout: 30000,
  verbose: true,
  capabilities: {
    host: 'HOST',
    user: 'USER',
    password: 'PASSWD',
    specs: '../tests/features/**puppeteer*.feature',
    name: process.env.BUILD_TAG,
    platform: 'ANY',
    browserName: 'chrome',
    version: '',
    shardTestFiles: false,
    maxInstances: 1,
    screenResolution: '1920x1080',
    timeZone: 'UTC',
    maxDuration: '10800',
    idleTimeout: 300,
    
    'goog:chromeOptions': { w3c: false },
    chromeOptions: {
      args: ['--test-type=browser', '--no-sandbox'],
      prefs: {
        download: {
          prompt_for_download: false,
          directory_upgrade: true,
          default_directory: downloadloc
        }
      },
      perfLoggingPrefs: {
        enableNetwork: true,
        enablePage: true,
        traceCategories:'blink.console,devtools.timeline,disabled-by-default-devtools.timeline,toplevel,disabled-by-default-devtools.timeline.frame,benchmark'
      },
      w3c: false,
    },
    
    loggingPrefs: {
      performance: 'ALL'
    }
  },
  cucumberOpts: {
    'tags': '',
    'format': ['progress', `json:reports/json/${cucumberReportName}`, 'node_modules/cucumber-pretty'],
    'require': ['../tests/step_definitions/**/*.js', 'support/*.js', './stepHooks.js'],
    'format-options': JSON.stringify({ 'snippetInterface': 'promise' }),
    'retry': '0'
  },
  beforeLaunch: () => {
    let mkdirp = require('mkdirp');
    mkdirp(this.config.jsonReportsDirOutput, (err) => {
      if (err) {
        throw err;
      }
    });
  },
  onPrepare: () => {
    let support = require('../config/prepareTests.js')(),
      e2eUtils = require('../tests/support/methods/e2eUtils.js')();
    return browser.getProcessedConfig()
      .then((conf) => {
        browser.addMockModule('disableNgAnimate', support.disableNgAnimate);
        browser.addMockModule('disableCssAnimate', support.disableCssAnimate);
        browser.addMockModule('disableDebounce', support.disableDebounce);
        browser.e2eUtils = e2eUtils;
        browser.host = conf.capabilities.host;
        browser.defaultUser = {
          hostName: conf.capabilities.host,
          userName: conf.capabilities.user,
          password: conf.capabilities.password
        };
        return support.getBrowserConfig(browser.defaultUser, conf.capabilities.host)
          .then(() => {
            return browser.getCapabilities()
              .then((caps) => {
                browser.browserName = caps.get('browserName');
                console.log('Tests are run on: ' + browser.browserName);
              });
          });
      });
  },
  params: {
    perf: {
      selenium: {
        protocol: 'http',
        slashes: true,
        auth: null,
        host: '127.0.0.1:4444',
        port: '4444',
        hostname:'127.0.0.1',
        hash: null,
        search: null,
        query: null,
        pathname: '/wd/hub',
        path: '/wd/hub',
        href: 'http://127.0.0.1:4444/wd/hub'
      },
      browsers: [
        {
          host: 'HOST',
          user: 'USER',
          password: 'PASSWD',
          specs: '../tests/features/**puppeteer*.feature',
          browserName: 'chrome',
          version: '',
          shardTestFiles: false,
          maxInstances: 1,
          screenResolution: '1920x1080',
          timeZone: 'Berlin',
          maxDuration: '10800',
          idleTimeout: 300,
          
          chromeOptions: {
            args: ['--test-type=browser', '--no-sandbox'],
            prefs: {
              download: {
                prompt_for_download: false,
                directory_upgrade: true,
                default_directory: downloadloc
              }
            },
            perfLoggingPrefs: {
              enableNetwork: true,
              enablePage: true,
              traceCategories:'blink.console,devtools.timeline,disabled-by-default-devtools.timeline,toplevel,disabled-by-default-devtools.timeline.frame,benchmark'
            },
            w3c: false,
          },
          
          loggingPrefs: {
            performance: 'ALL'
          }
        }
      ],
      debugBrowser: false,
      actions: ['scroll'],
      metrics:[
        'TimelineMetrics',
        'ChromeTracingMetrics',
        'RafRenderingStats',
        'NetworkTimings',
        'NetworkResources'
      ]
    }
  },
  plugins: [
    {
      package: 'protractor-puppeteer-plugin',
      configFile: './config/puppeteer.conf.json',
    }
  ]
};
```

If you have any hints, I would be happy :)

**Comment by And93** [comment]
Hi @ajoecker ,
Could you please change your `puppeteer.conf.json` to:
```
{
  "connectToBrowser": true,
  "timeout": 30000,
  "logLevel": "info"
}
```

**Comment by ajoecker** [comment]
that helped - thank you
